services:
  - type: web
    name: fireworks-planner
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt && pip install gunicorn"
    startCommand: "cd backend && gunicorn server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
    disk:
      name: videos-storage
      mountPath: /opt/render/project/src/backend/videos
      sizeGB: 1

