services:
  - type: web
    name: fireworks-planner
    runtime: python
    buildCommand: "curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs && cd backend && pip install -r requirements.txt && pip install gunicorn && yt-dlp --update"
    startCommand: "cd backend && gunicorn server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
    disk:
      name: videos-storage
      mountPath: /opt/render/project/src/backend/videos
      sizeGB: 1

